#:schema ../../../schema/inference.schema.json

save_preview_dir = "./demo/inference_flux_tie_preview"

hsdp_shard_dim = 1

[model]
arch = "flux1"
type = "kontext"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_flux_tie"

[sampler]
type = "linear_shift"
steps = 20
cfg_scale = 1.0

[processor]
task = "tie"
preset = "flux1"

[launch]
type = "inference"
devices = 4
# preprocess_config = "./examples/tie/flux1/preprocess.toml"