#:schema ../../../schema/inference.schema.json

save_preview_dir = "./demo/inference_flux_t2i_preview"

hsdp_shard_dim = 1

[model]
arch = "flux1"
type = "base"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_flux_t2i"

[sampler]
steps = 20
cfg_scale = 1.0

[sampler.shift]
type = "linear"

[processor]
task = "t2i"
preset = "flux1"

[launch]
type = "inference"
devices = 4
preprocess_config = "examples/t2i/flux1/preprocess.toml"
