save_preview_dir = "./demo/inference_longcat_tie_preview"

hsdp_shard_dim = 1

[model]
arch = "longcat"
type = "edit"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_longcat_tie"

[sampler]
type = "linear_shift"
steps = 50
cfg_scale = 4.5
enable_cfg_renorm = true

[processor]
task = "tie"
preset = "longcat_image_edit"

[launch]
type = "inference"
devices = 4
preprocess_config = "examples/tie/longcat/preprocess.toml"

[launch.env]
NCCL_CUMEM_HOST_ENABLE = "0"
NCCL_P2P_LEVEL = "SYS"