#:schema ../../../schema/sft.schema.json

checkpoint_root = "./runs/sft/flux"
# seed_checkpoint_dir = "./runs/sft/flux/seed"
seed_checkpoint_dir = "/dev/shm/flow-control/seed"
aim_repo = "aim://192.168.6.132:53800"
experiment_name = "flux_sft_demo"
checkpoint_limit = 10
validation_steps = 20
checkpoint_steps = 20

gradient_checkpointing = true
global_batch_size = 16
train_steps = 200
ema_decay = 1.0

hsdp_shard_dim = 1

[model]
arch = "flux1"
type = "base"
peft_lora_rank = 16

[sampler]
type = "linear_shift"
steps = 20
cfg_scale = 1.0

[processor]
task = "t2i"
preset = "flux1"

[optimizer]
class_name = "AdamW"
lr = 5e-4

[scheduler]
class_name = "ConstantLR"
factor = 1.0

[dataset]
type = "pickle_directory"
path = "./data/christian_boragine/flux1"

[validation_dataset]
type = "pickle_directory"
path = "./data/christian_boragine/flux1_validation"

[launch]
type = "sft"
devices = 4
generate_dcp_seed = true