#:schema ../../../schema/inference.schema.json

seed_checkpoint_dir = "/dev/shm/flow-control/seed"
save_preview_dir = "./demo/inference_flux2_tie_preview"

hsdp_shard_dim = 2

[model]
arch = "flux2"
type = "base"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_flux2_tie"

[sampler]
steps = 28
cfg_scale = 1.0

[sampler.shift]
type = "flux2"

[processor]
task = "tie"
preset = "flux2"
resize_mode = "multiple_of"
total_pixels = 1048576 # 1024 * 1024

[launch]
type = "inference"
devices = 4
generate_dcp_seed = true
# preprocess_config = "examples/tie/flux2/preprocess.toml"

[launch.env]
NCCL_CUMEM_HOST_ENABLE = "0"
NCCL_P2P_LEVEL = "SYS"
