#:schema ../../../schema/inference.schema.json

save_preview_dir = "./demo/inference_qwen_tie_preview"

hsdp_shard_dim = 1

[model]
arch = "qwen"
type = "edit"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_qwen_tie"

[sampler]
type = "linear_shift"
steps = 28
max_image_seq_len = 8192
max_shift = 0.9
cfg_scale = 4.0
enable_cfg_renorm = true

[processor]
task = "tie"
preset = "qwen_image_edit"

[launch]
type = "inference"
devices = 4
# preprocess_config = "examples/tie/qwen/preprocess.toml"