seed_checkpoint_dir = "./demo/seed/flux2"
save_preview_dir = "./demo/inference_flux2_t2i_preview"

hsdp_shard_dim = 4

[model]
arch = "flux2"
type = "base"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_flux2_t2i"

[sampler]
type = "flux2_shift"
steps = 28
cfg_scale = 1.0

[processor]
task = "t2i"
preset = "flux2"

[launch]
type = "inference"
devices = 4

[launch.env]
NCCL_CUMEM_HOST_ENABLE = "0"
NCCL_P2P_LEVEL = "SYS"