#:schema ../../../schema/inference.schema.json

save_preview_dir = "./demo/inference_flux2_klein_9b_t2i_preview"

hsdp_shard_dim = 1

[model]
arch = "flux2"
type = "base"

[model.hf_model]
library = "diffusers"
class_name = "Flux2Transformer2DModel"
pretrained_model_id = "black-forest-labs/FLUX.2-klein-9B"
subfolder = "transformer"
dtype = "bfloat16"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_flux2_klein_9b_t2i"

[sampler]
steps = 4
cfg_scale = 1.0

[sampler.shift]
type = "flux2"

[processor]
task = "t2i"
preset = "flux2_klein_9b"

[launch]
type = "inference"
devices = 4
preprocess_config = "examples/t2i/flux2/preprocess_klein_9b.toml"
