checkpoint_root = "./runs/geneval_flux/"
seed_checkpoint_dir = "/dev/shm/flow-control/seed"
aim_repo = "aim://192.168.5.62:53800"
experiment_name = "flux_grpo_demo"

num_batches_per_epoch = 12
num_prompts_per_batch = 4
num_rollouts_per_prompt = 24
num_inner_epochs = 1
train_batch_size = 1728

clip_grad_norm = 1.0
clip_range = 1e-5
kl_beta = 0.0

timestep_selection = "random_contiguous"
timestep_window_size = 3

train_epochs = 1000
checkpoint_epochs = 10
validation_epochs = 10

[model]
arch = "flux1"
type = "base"
peft_lora_rank = 32

[dataset]
type = "pickle_directory"
path = "./data/geneval_flux/train"

[train_sampler]
type = "linear_shift"
steps = 6
cfg_scale = 1.0
noise_level = 0.8
sde_type = "cps"

[ema]
decay = 0.9
warmup = true
interval = 1

[reward]
type = "geneval"
checkpoint_path = "./data/swin_small_patch4_window7_224.pth"

[advantage]
type = "per_prompt"

[optimizer]
class_name = "AdamW"
lr = 3e-4
weight_decay = 1e-4

[scheduler]
class_name = "ConstantLR"
factor = 1.0

# Validation

[validation_dataset]
type = "pickle_directory"
path = "./data/geneval_flux/validation"

[sampler]
type = "linear_shift"
steps = 28
cfg_scale = 1.0

[processor]
task = "t2i"
preset = "flux1"
default_resolution = [512, 512]

[launch]
type = "grpo"
devices = 4
generate_dcp_seed = true